name: Tests

on:
  pull_request:
  push:
    branches: [master]

jobs:
  test_importsession:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install ffmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Install dependencies
        run: pip install beets flask

      - name: Run test_importsession.py
        run: python test_importsession.py
